### PR TITLE
1.4.1

### PR DESCRIPTION
**Pull request by djsutherland**
Closes #7, closes #8, closes #9, and closes #10.

@scottgigante, I additionally switched to PyPI source instead of github (generally preferred). When you put out the next release after https://github.com/KrishnaswamyLab/graphtools/pull/48, you can delete the `LICENSE` file from the recipe (and the comment).

In the future, you'll probably get a faster response if you tag conda-forge/core instead of me specifically. Also, it's nice if you check the "allow edits from maintainers" box so I don't have to make a new PR like this for small tweaks. :)

### CODE REVIEW

**Comment by scottgigante** [comment]
Thanks @dougalsutherland ! I thought the @ core tag didn't work because I tried it before -- turns out it's only available to members of the organization (which I am now). 

I've bumped to 1.4.1 which will have the LICENSE in the tarball, should be on pypi shortly. Thanks for fixing this up!

**Comment by djsutherland** [comment]
Yep, you have to be a member to ping teams (slightly confusing github behavior).

I'll check back in a bit to see if 1.4.1's popped up, to avoid cruft in the recipe; feel free to ping me specifically when it does though. :)

**Comment by scottgigante** [comment]
Thanks @dougalsutherland . It's up! sha256 169e4be6722a75236584cc7a16987bb04d9037549123e7c615f51e69ab145611

**Comment by scottgigante** [comment]
Thanks!

**Pull request merged**
